#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
EXTERNAL_DIR="${REPO_ROOT}/external"
INVENTORY_FILE="${SCRIPT_DIR}/inventories/dev.ini"

error() {
  echo "[ERROR] $1" >&2
  exit 1
}

if ! command -v terraform >/dev/null 2>&1; then
  error "terraform not found. Install Terraform first."
fi

if ! command -v jq >/dev/null 2>&1; then
  error "jq not found. Install jq first."
fi

if [[ ! -d "${EXTERNAL_DIR}" ]]; then
  error "external directory not found: ${EXTERNAL_DIR}"
fi

if ! terraform -chdir="${EXTERNAL_DIR}" state pull >/dev/null 2>&1; then
  error "Terraform state is not available. Run 'terraform -chdir=external init' and 'terraform -chdir=external apply' first."
fi

if ! TF_OUTPUT_JSON="$(terraform -chdir="${EXTERNAL_DIR}" output -json 2>/dev/null)"; then
  error "Failed to read Terraform outputs. Apply may not be complete."
fi

external_bastion_public_ip="$(echo "${TF_OUTPUT_JSON}" | jq -r '.external_bastion_public_ip.value // ""')"
readarray -t web_private_ips < <(echo "${TF_OUTPUT_JSON}" | jq -r '.web_private_ips.value[]?')
readarray -t was_private_ips < <(echo "${TF_OUTPUT_JSON}" | jq -r '.was_private_ips.value[]?')

if [[ -z "${external_bastion_public_ip}" ]]; then
  error "No external_bastion_public_ip found in Terraform outputs."
fi

if [[ ${#web_private_ips[@]} -eq 0 ]]; then
  error "No web_private_ips found in Terraform outputs."
fi

if [[ ${#was_private_ips[@]} -eq 0 ]]; then
  error "No was_private_ips found in Terraform outputs."
fi

{
  echo "# Generated by ansible/generate_inventory.sh"
  echo "# External bastion public IP: ${external_bastion_public_ip}"
  echo "# Optional ProxyJump example (when running Ansible outside bastion):"
  echo "# ansible_ssh_common_args='-o ProxyJump=dev1@${external_bastion_public_ip}'"
  echo

  echo "[web]"
  for i in "${!web_private_ips[@]}"; do
    host_index=$((i + 1))
    echo "web${host_index} ansible_host=${web_private_ips[$i]}"
  done
  echo

  echo "[was]"
  for i in "${!was_private_ips[@]}"; do
    host_index=$((i + 1))
    echo "was${host_index} ansible_host=${was_private_ips[$i]}"
  done
  echo

  echo "[all:vars]"
  echo "ansible_user=dev1"
  if [[ -n "${ANSIBLE_PRIVATE_KEY_FILE:-}" ]]; then
    echo "ansible_ssh_private_key_file=${ANSIBLE_PRIVATE_KEY_FILE}"
  fi
  echo "external_bastion_public_ip=${external_bastion_public_ip}"
} > "${INVENTORY_FILE}"

echo "Generated ${INVENTORY_FILE}"
echo "External bastion public IP: ${external_bastion_public_ip}"